drop table if exists member CASCADE;

create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

INSERT into member(name) values('spring');
INSERT into member(name) values('spring2');

SELECT * FROM MEMBER;